# Generated by Django 4.0 on 2023-01-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('paradox', '0003_profile_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Art', 'Art'), ('History', 'History'), ('Technology', 'Technology'), ('Business', 'Business')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='files/flashcard title images'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='title',
            field=models.CharField(max_length=999, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='flashcard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paradox.flashcard'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
