# Generated by Django 4.0 on 2023-02-03 09:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0004_flashcard_author_flashcard_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
