# Generated by Django 4.0 on 2023-02-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0005_flashcard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='featured_image',
            field=models.ImageField(help_text='upload an image with a resolution of 375x360', null=True, upload_to='files/flashcard title images'),
        ),
    ]
