# Generated by Django 4.0 on 2023-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0006_alter_flashcard_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
