# Generated by Django 4.0 on 2023-02-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0008_alter_flashcard_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
